version: '3.9'
services:
  consul:
    image: consul:latest
    ports:
      - "8500:8500"
  uuidgenerator:
    image: uuidgenerator
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
    - consul
    links:
    - "consul"
