version: '3.9'

services:
  cassandra:
    image: docker.io/bitnami/cassandra:latest
    ports:
      - '7000:7000'
      - '9042:9042'
    environment:
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
  bookstore-service:
    image: bookstore-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
