CREATE TABLE credit_card (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  card_number VARCHAR(255) NOT NULL,
  balance INT(11) UNSIGNED,
  account_limit INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX UNIQUE_KEY (card_number)
) ENGINE=INNODB DEFAULT CHARSET=utf8;