server:
  port: 4444

application:
  topic:
    message-topic: demo-kafka-topic

spring:
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
