application:
  api:
    version: v1

server:
  servlet:
    context-path: /credit-card-processing-service/${application.api.version}
  port: 9999

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration