version: '3.9'
services:
  consul:
    image: consul:latest
    ports:
      - "8500:8500"
  uuidgenerator:
    image: uuidgenerator
    ports:
      - "8888:8888"
    depends_on:
      - consul
    links:
      - "consul"
  clientidgenerator:
    image: clientidgenerator
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8889:8889"
