server:
  port: 5555

application:
  topic:
    message-topic: demo-kafka-topic

spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: demo-kafka-consumer
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: "springboot.kafka.docker.kafka_producer.model"
            value:
              default:
                type: "springboot.kafka.docker.kafka_consumer.model.Message"

    listener:
      concurrency: 3
      ack-mode: manual